project:
- TCGA-BRCA

profiles:
  - simple_nucleotide_variation
  - copy_number_variation
  - trancriptome_profiling
  - dna_methylation
  - protein_profiling
  - clinical
  - somatic_structural_variation